import re
from typing import Dict, Optional

from src.models.db import RawIssueComment, RawPullRequest, RawReview, RawReviewComment, ReviewItem


class Normalizer:
    """Normalizes raw GitHub data into structured ReviewItems."""

    BOT_PATTERNS = [
        r"codecov",
        r"dependabot",
        r"github-actions",
        r"sonar",
        r"snyk",
        r"lgtm",
        r"lint",
    ]

    LANGUAGE_MAP = {
        ".py": "python",
        ".js": "javascript",
        ".ts": "typescript",
        ".tsx": "typescript",
        ".jsx": "javascript",
        ".cpp": "cpp",
        ".hpp": "cpp",
        ".c": "c",
        ".h": "c",
        ".go": "go",
        ".rs": "rust",
        ".java": "java",
        ".kt": "kotlin",
        ".rb": "ruby",
        ".php": "php",
        ".swift": "swift",
        ".m": "objective-c",
        ".sh": "shell",
        ".yml": "yaml",
        ".yaml": "yaml",
        ".json": "json",
        ".md": "markdown",
    }

    def __init__(self, redact_identity: bool = True):
        self.redact_identity = redact_identity

    def is_bot(self, author: str, body: str) -> bool:
        """Determine if the comment was generated by a bot."""
        author_lower = author.lower()
        body_lower = body.lower()

        for pattern in self.BOT_PATTERNS:
            if re.search(pattern, author_lower) or re.search(pattern, body_lower):
                return True
        return False

    def estimate_language(self, file_path: Optional[str]) -> Optional[str]:
        """Estimates the programming language from file extension."""
        if not file_path:
            return None

        for ext, lang in self.LANGUAGE_MAP.items():
            if file_path.endswith(ext):
                return lang
        return "unknown"

    def parse_diff_hunk(self, diff_hunk: Optional[str]) -> Dict[str, Optional[str]]:
        """
        Parse GitHub diff hunk to extract context.

        Extracts original (before) and modified (after) versions of the code.
        """
        if not diff_hunk:
            return {"before": None, "after": None}

        lines = diff_hunk.splitlines()
        # Skip the @@ -L,C +L,C @@ header if present
        if lines and lines[0].startswith("@@"):
            lines = lines[1:]

        before_lines = []
        after_lines = []

        for line in lines:
            if line.startswith("-"):
                before_lines.append(line[1:])
            elif line.startswith("+"):
                after_lines.append(line[1:])
            else:
                # Context line (space prefix or empty)
                content = line[1:] if line.startswith(" ") else line
                before_lines.append(content)
                after_lines.append(content)

        return {
            "before": "\n".join(before_lines).strip() if before_lines else None,
            "after": "\n".join(after_lines).strip() if after_lines else None,
        }

    def normalize_review_comment(
        self, repo: str, pr: RawPullRequest, comment: RawReviewComment
    ) -> Optional[ReviewItem]:
        """Normalize a single review comment."""
        author = comment.raw_data.get("user", {}).get("login", "unknown")

        if self.is_bot(author, comment.body):
            return None

        # Redact identity if configured
        author_redacted = "redacted_user" if self.redact_identity else author

        language = self.estimate_language(comment.path)
        diff_context = self.parse_diff_hunk(comment.diff_hunk)

        return ReviewItem(
            id=f"ri_rc_{comment.id}",
            repo=repo,
            pr_number=pr.pr_number,
            source_type="review_comment",
            source_id=comment.id,
            file_path=comment.path,
            language=language,
            code_context_before=diff_context["before"],
            code_context_after=diff_context["after"],
            diff_hunk=comment.diff_hunk,
            comment_text=comment.body,
            author_redacted=author_redacted,
            created_at=comment.created_at,
        )

    def normalize_issue_comment(
        self, repo: str, pr: RawPullRequest, comment: RawIssueComment
    ) -> Optional[ReviewItem]:
        """Normalize an issue comment (PR thread comment)."""
        author = comment.raw_data.get("user", {}).get("login", "unknown")

        if self.is_bot(author, comment.body):
            return None

        author_redacted = "redacted_user" if self.redact_identity else author

        return ReviewItem(
            id=f"ri_ic_{comment.id}",
            repo=repo,
            pr_number=pr.pr_number,
            source_type="issue_comment",
            source_id=comment.id,
            comment_text=comment.body,
            author_redacted=author_redacted,
            created_at=comment.created_at,
        )

    def normalize_review_summary(
        self, repo: str, pr: RawPullRequest, review: RawReview
    ) -> Optional[ReviewItem]:
        """Normalize a review summary (general review feedback)."""
        if not review.body:
            return None

        author = review.raw_data.get("user", {}).get("login", "unknown")

        if self.is_bot(author, review.body):
            return None

        author_redacted = "redacted_user" if self.redact_identity else author

        return ReviewItem(
            id=f"ri_rs_{review.id}",
            repo=repo,
            pr_number=pr.pr_number,
            source_type="review_summary",
            source_id=review.id,
            comment_text=review.body,
            review_state=review.state,
            author_redacted=author_redacted,
            created_at=review.submitted_at,
        )
